id: I735C3E70
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T13:39:55+00:00'
last_modified: '2022-06-08T02:07:37.343107+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN7048
  title: ལྷོ་ཁའི་གྲགས་ཅན་མི་སྣ་རིམ་བྱོན་གྱི་མཚན་མཛོད་ཉི་ཁུག་གི་རྒད་པོ་དང་མོས་པའི་གཏམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    4A2A:
      image_group_id: I3CN7050
      title: ''
      total_pages: 560
      order: 1
      base_file: 4A2A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
